##
## EPITECH PROJECT, 2019
## 101pong
## File description:
## Makefile
##

MAIN = src/main.py

NAME = my_breakout

all: $(NAME)

$(NAME):
	cp $(MAIN) ./$(NAME)
	chmod +x $(NAME)

fclean:
	rm -f $(NAME)

re: fclean all
